### ISSUE TITLE
Job stucked boquing futher indexing

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Solr#3]
I have a solr indexing job which failed. Solr core was restarting during the indexing I guess. This job was in statut "en cours" in Omeka S job management page. I stopped it and it is now in status 
 "Arrêt en cours".

Since this, each time I launch a solr indexing process, even when I force the job, I have the following message:

```
2019-03-14T07:37:04+00:00 INFO (6): Search index #1 ("solr"): start of indexing
2019-03-14T07:37:04+00:00 ERR (3): Search index #1 ("solr"): end of indexing: there are already 1 other jobs "Search Index" and the current one is not forced.

```

How can I definitively get rid of this stucked job?

**Comment by Daniel-KM** [comment]
Can you post this issue in the omeka s issues?

**Comment by pprw** [comment]
I fixed this issue by deleting directly from the mysql database the line corresponding to the stucked job. This is a very particular issue (I guess I was doing some modification of Solr and reindexing in the same time) so it is probably not a bug.

Sorry for not closing this myself sooner.
