### ISSUE TITLE
No configuration options for core path

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Solr#4]
I just installed "Search adapter for Solr", "Solr" (and "jQueryUI ") modules on a fresh new Omeka S installation.

I cannot find where are the options to configure the path of the core. Contrary to previous versions of this module, there is now no configuration options in /admin/module, in the site settings or below the Search button inside Admin settings.

I'm probably missing something.

**Comment by Daniel-KM** [comment]
There is no change on that point, but module search version and module solr versions should be the last ones.

**Comment by Daniel-KM** [comment]
And yes, there is no config inside /admin/module, all are in /admin/search-manager

**Comment by pprw** [comment]
Ok, it works now. 

I was using Search biblibre's version, which is linked in the description of the current (forked) Solr module (https://github.com/Daniel-KM/Omeka-S-module-Solr) although it is not currently compatible with it (ie with your fork of solr module).
