### ISSUE TITLE
"is secure" options not available

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Solr#5]
After installing last versions of your forks of Search/Solr, I don't have the options "is secure" "solr login" "solr password" which allow to connect to a protected solr instance.

I can connect anyway with the login and password inside the server URL (login:password@ip_server) but is this fallback expected?

**Comment by Daniel-KM** [comment]
I don't understand why you don't see the options. They are in Search > Solr > edit.

**Comment by pprw** [comment]
Sorry I was using [biblibre's version of Search  ](https://github.com/biblibre/omeka-s-module-Search) instead of [yours](https://github.com/Daniel-KM/omeka-s-module-Search).

In the README of this module, links to "Search" module should probably be replaced with links toward your fork.
