### ISSUE TITLE
Solr HTTP Error 35: 'SSL connect error'

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Solr#6]
After installing current master version (yours) of Search and Solr, I have the following error:
`Solr HTTP Error 35: 'SSL connect error' `

The same configurations options works on previous versions of Solr/Search. It seems current version had "https://" automatically for the host which is maybe the source of the issue in my case. What do you think?

**Comment by Daniel-KM** [comment]
You can disable the certificate check. Add this to your `config/local.config.php`: 

```php
    'solr' => [
        'config' => [
            'solr_bypass_certificate_check' => true,
        ],
    ],
```
