### ISSUE TITLE
Indexing and configuring mapping fail with errors in Omeka-S v. 2.0.1

### ISSUE THREAD

**Issue by julia-bauder** [Daniel-KM/Omeka-S-module-Solr#7]
In Omeka-S v. 2.0.1, any attempt to modify the mapping or to re-index the site results in the following error:

Doctrine\ORM\Query\QueryException
[Syntax Error] line 0, col 69: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got 'Solr\Entity\SolrMapping'

Details:

Doctrine\ORM\Query\QueryException: SELECT omeka_root FROM Solr\Entity\SolrMapping omeka_root INNER JOIN Solr\Entity\SolrMapping.solrNode omeka_0 WHERE omeka_0.id = :omeka_1 AND Solr\Entity\SolrMapping.resourceName = :omeka_2 GROUP BY omeka_root.id ORDER BY omeka_root.id ASC in /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43
Stack trace:
#0 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(456): Doctrine\ORM\Query\QueryException::dqlError('SELECT omeka_ro...')
#1 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(324): Doctrine\ORM\Query\Parser->syntaxError('Doctrine\\ORM\\Qu...')
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(923): Doctrine\ORM\Query\Parser->match(102)
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1042): Doctrine\ORM\Query\Parser->IdentificationVariable()
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1766): Doctrine\ORM\Query\Parser->JoinAssociationPathExpression()
#5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1700): Doctrine\ORM\Query\Parser->JoinAssociationDeclaration()
#6 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1596): Doctrine\ORM\Query\Parser->Join()
#7 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1319): Doctrine\ORM\Query\Parser->IdentificationVariableDeclaration()
#8 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(878): Doctrine\ORM\Query\Parser->FromClause()
#9 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(847): Doctrine\ORM\Query\Parser->SelectStatement()
#10 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(260): Doctrine\ORM\Query\Parser->QueryLanguage()
#11 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(359): Doctrine\ORM\Query\Parser->getAST()
#12 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query\Parser->parse()
#13 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(295): Doctrine\ORM\Query->_parse()
#14 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(967): Doctrine\ORM\Query->_doExecute()
#15 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(922): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#16 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(726): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#17 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(173): Doctrine\ORM\AbstractQuery->getResult(1)
#18 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(257): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#19 /var/www/html/application/src/Api/Manager.php(221): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#20 /var/www/html/application/src/Api/Manager.php(59): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#21 /var/www/html/application/src/Mvc/Controller/Plugin/Api.php(63): Omeka\Api\Manager->search('solr_mappings', Array, Array)
#22 /var/www/html/modules/Solr/src/Controller/Admin/MappingController.php(72): Omeka\Mvc\Controller\Plugin\Api->search('solr_mappings', Array)
#23 /var/www/html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Solr\Controller\Admin\MappingController->browseResourceAction()
#24 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#25 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /var/www/html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(104): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#27 /var/www/html/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#28 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#29 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#30 /var/www/html/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#31 /var/www/html/index.php(21): Zend\Mvc\Application->run()
#32 {main}

Next Doctrine\ORM\Query\QueryException: [Syntax Error] line 0, col 69: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got 'Solr\Entity\SolrMapping' in /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:54
Stack trace:
#0 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(456): Doctrine\ORM\Query\QueryException::syntaxError('line 0, col 69:...', Object(Doctrine\ORM\Query\QueryException))
#1 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(324): Doctrine\ORM\Query\Parser->syntaxError('Doctrine\\ORM\\Qu...')
#2 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(923): Doctrine\ORM\Query\Parser->match(102)
#3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1042): Doctrine\ORM\Query\Parser->IdentificationVariable()
#4 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1766): Doctrine\ORM\Query\Parser->JoinAssociationPathExpression()
#5 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1700): Doctrine\ORM\Query\Parser->JoinAssociationDeclaration()
#6 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1596): Doctrine\ORM\Query\Parser->Join()
#7 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1319): Doctrine\ORM\Query\Parser->IdentificationVariableDeclaration()
#8 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(878): Doctrine\ORM\Query\Parser->FromClause()
#9 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(847): Doctrine\ORM\Query\Parser->SelectStatement()
#10 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(260): Doctrine\ORM\Query\Parser->QueryLanguage()
#11 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(359): Doctrine\ORM\Query\Parser->getAST()
#12 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query\Parser->parse()
#13 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(295): Doctrine\ORM\Query->_parse()
#14 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(967): Doctrine\ORM\Query->_doExecute()
#15 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(922): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#16 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(726): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#17 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(173): Doctrine\ORM\AbstractQuery->getResult(1)
#18 /var/www/html/application/src/Api/Adapter/AbstractEntityAdapter.php(257): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#19 /var/www/html/application/src/Api/Manager.php(221): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#20 /var/www/html/application/src/Api/Manager.php(59): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#21 /var/www/html/application/src/Mvc/Controller/Plugin/Api.php(63): Omeka\Api\Manager->search('solr_mappings', Array, Array)
#22 /var/www/html/modules/Solr/src/Controller/Admin/MappingController.php(72): Omeka\Mvc\Controller\Plugin\Api->search('solr_mappings', Array)
#23 /var/www/html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Solr\Controller\Admin\MappingController->browseResourceAction()
#24 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#25 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /var/www/html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(104): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#27 /var/www/html/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#28 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#29 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#30 /var/www/html/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#31 /var/www/html/index.php(21): Zend\Mvc\Application->run()
#32 {main}

**Comment by pprw** [comment]
You should use code markup to avoid referring to other issue (with # sign).

inline code: \`code\` -> `code`

multi-lines code:

\```
code
code
\```

```
code
code
```

**Comment by pprw** [comment]
I think there is a good chance modules need a upgrade before being usable in Omeka S >=2.0 version.

**Comment by Daniel-KM** [comment]
I'm working on it, it will be available Monday.

**Comment by Daniel-KM** [comment]
Yes, it is available.
