### ISSUE TITLE
Checking `is secure` option prevent connecting to server

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Solr#8]
On a secure server, if `is secure` is ticked,  Solr module cannot connect to the server.

When this option is unticked, even if the server where solr is installed need authentication, the connection is established.

**Comment by pprw** [comment]
It is probably server related.

**Comment by Daniel-KM** [comment]
Yes, authentification is always complex and to be adapted to the system. 
You can add that to your config/local.config.php to bypass checks: 
```php
    'solr' => [
        'config' => [
            'solr_bypass_certificate_check' => true,
        ],
    ],
```
